### ISSUE TITLE
Fix crash that occurs sometimes, when we try to connect to a Bluetooth device we are already connected to

### ISSUE THREAD

**Issue by sandy-8925** [sandy-8925/BLExplorer#7]
Stacktrace:

2021-02-27 16:16:48.866 29233-29233/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.ligi.blexplorer, PID: 29233
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | com.polidea.rxandroidble2.exceptions.BleAlreadyConnectedException: Already connected to device with MAC address FF:FF:AE:46:A4:80
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at com.uber.autodispose.HalfSerializer.onError(HalfSerializer.java:148)
        at com.uber.autodispose.AutoDisposingObserverImpl.onError(AutoDisposingObserverImpl.java:88)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:281)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: com.polidea.rxandroidble2.exceptions.BleAlreadyConnectedException: Already connected to device with MAC address FF:FF:AE:46:A4:80
        at com.polidea.rxandroidble2.internal.RxBleDeviceImpl$1.call(RxBleDeviceImpl.java:84)
        at com.polidea.rxandroidble2.internal.RxBleDeviceImpl$1.call(RxBleDeviceImpl.java:72)
        at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:33)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableDoOnLifecycle.subscribeActual(ObservableDoOnLifecycle.java:33)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableDoOnEach.subscribeActual(ObservableDoOnEach.java:42)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservablePublishAlt.connect(ObservablePublishAlt.java:79)
        at io.reactivex.internal.operators.observable.ObservableRefCount.subscribeActual(ObservableRefCount.java:87)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at com.jakewharton.rx.ReplayingShare$LastSeenObservable.subscribeActual(ReplayingShare.java:78)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableFlatMapSingle.subscribeActual(ObservableFlatMapSingle.java:48)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableFlatMapSingle.subscribeActual(ObservableFlatMapSingle.java:48)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at com.uber.autodispose.AutoDisposeObservable.subscribeActual(AutoDisposeObservable.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.Observable.subscribe(Observable.java:12270)
        at io.reactivex.Observable.subscribe(Observable.java:12172)
        at com.uber.autodispose.AutoDispose$1$4.subscribe(AutoDispose.java:267)
        at org.ligi.blexplorer.characteristics.CharacteristicActivity.onCreate(CharacteristicActivity.kt:82)

**Comment by sandy-8925** [comment]
Should hopefully be fixed with https://github.com/sandy-8925/BLExplorer/commit/f17ec7dbdc3b6bd610179df0ba51a08078939804 and https://github.com/sandy-8925/BLExplorer/commit/9c3e10db81d2d3309ebf6687279c8112235228ee

**Comment by sandy-8925** [comment]
Closing for now, will reopen if the crash re-occurs.
